### ISSUE TITLE
CCO Travis pipeline failing

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#232]
Adam to determine if this affects just the CCO or all deployments

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by woodt** [comment]
I created a branch based on master with no other changes, and it fails repeatedly setting up the minikube provider:

```
2020-02-06 14:16 INFO (start_time="2020-02-06 14:16:57.089615") Waiting for instance events
2020-02-06 14:18 INFO Still waiting for ['ckan-entrypoint-db-init-success', 'ckan-entrypoint-extra-init-success', 'ckan-entrypoint-initialized', 'ckan-env-vars-created/ckan-env-vars-exists', 'ckan-secrets-created/ckan-secrets-exists', 'got-ckan-secrets']
2020-02-06 14:19 INFO 72 seconds since started waiting
2020-02-06 14:20 INFO 145 seconds since started waiting
2020-02-06 14:21 INFO 218 seconds since started waiting
2020-02-06 14:23 INFO 290 seconds since started waiting
2020-02-06 14:24 INFO 363 seconds since started waiting
2020-02-06 14:25 INFO 435 seconds since started waiting
2020-02-06 14:26 INFO 508 seconds since started waiting
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/ckan-cloud-operator", line 11, in <module>
    load_entry_point('ckan-cloud-operator', 'console_scripts', 'ckan-cloud-operator')()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/cli.py", line 34, in create
    wait_ready=wait_ready, skip_deployment=skip_deployment, skip_route=skip_route, force=force)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/manager.py", line 70, in create
    dry_run=dry_run)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/manager.py", line 104, in update
    deployment_manager.update(instance_id, instance_type, instance, force=force)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/deployment/manager.py", line 7, in update
    return _get_deployment_provider(instance_type).update(instance_id, instance, force=force, dry_run=dry_run)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/deployment/helm/manager.py", line 84, in update
    _wait_instance_events(instance_id)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/deployment/helm/manager.py", line 376, in _wait_instance_events
    raise Exception('timed out waiting for instance events')
Exception: timed out waiting for instance events
The command "ckan-cloud-operator ckan instance create helm --instance-id a-ckan-instance --instance-name a-ckan-instance --update sample-values/values.datagov.yaml" exited with 1.
after_failure
8.65s$ minikube delete
Done. Your build exited with 1.

```

**Comment by akariv** [comment]
I will look into it, thanks for letting me know.

**Comment by estebanruseler** [comment]
This just affects CCO not the sandbox deployment. The only reason to do this is so that Tom's security features can be incorporated into CCO. Suggest we icebox this.
