### ISSUE TITLE
CKAN -> CKAN harvester

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#303]
## User Story
As a federal agency's data publisher, I want to describe my data in one place using federal standards and see it published on data.gov, so that I can comply with federal mandates in the fewest steps.

## Acceptance criteria
- [x] GIVEN I add a CKAN harvest source
  WHEN I trigger a harvest run of that source
  THEN the harvest is successful and the metadata is ingested and visible on the [DOI organization page](https://catalog-next.sandbox.datagov.us/organization/doi-gov)
  ~AND a message is delivered to SMTP server~ (covered in #315)

## Details/Tasks
- [x] Validate that CKAN to CKAN harvesting works in the local environment 
- [x] Validate that CKAN to CKAN harvesting works in the sandbox/staging environment

**Comment by avdata99** [comment]
Added `ckan_harvester` in `CKAN__PLUGINS` list and tested harvesting https://datos.gob.ar CKAN instance

Gather works:
![image](https://user-images.githubusercontent.com/3237309/82931184-e1a95500-9f5c-11ea-9d94-861f6405f1b7.png)

Fetch:
![image](https://user-images.githubusercontent.com/3237309/82931204-eb32bd00-9f5c-11ea-8851-f8c049d4e1ab.png)

And works fine
![image](https://user-images.githubusercontent.com/3237309/82931324-2503c380-9f5d-11ea-9af1-16cad8fee59c.png)

We need to add this as a PR

**Comment by avdata99** [comment]
[PR](https://github.com/GSA/catalog.data.gov/pull/37) sent

**Comment by estebanruseler** [comment]
Andres has finished checking that it works. This is all upstream code and looks like it's working. PR37 out for review. Next step would be for Tom & co to look at deploying in sandbox. 

Also, looking at acceptance criteria "THEN the harvest is successful and the metadata is ingested and visible on the *DOI organization page*" We assume this is a copy-paste issue, the org would not be the DOI but would be the particular org, yeah?

**Comment by hkdctol** [comment]
@estebanruseler do you mean when the CKAN to CKAN harvest finishes, it displays under the organization you set up in sandbox for it to go into? Then yes.

**Comment by estebanruseler** [comment]
@hkdctol thanks for confirming

**Comment by woodt** [comment]
Just as a "pre-test", I ran a harvest in the sandbox using the https://datos.gob.ar/ source @avdata99 mentioned above.  Some datasets were harvested correctly (yay!), but many failed with errors in the fetch stage like this:

```
2020-06-04 20:55:46,065 INFO  [ckanext.harvest.queue] Received harvest object id: c57481a8-8b8c-4584-a8c8-eda61b893904
2020-06-04 20:55:46,091 DEBUG [ckanext.harvest.harvesters.ckanharvester] In CKANHarvester import_stage
2020-06-04 20:55:46,143 INFO  [ckanext.harvest.harvesters.base] Package with GUID sspm_316 does not exist, let's create it
2020-06-04 20:55:46,215 DEBUG [ckanext.archiver.plugin] Notified of package event: sspm-ingreso-inversion-extranjera-directa-bcra new
2020-06-04 20:55:46,216 DEBUG [ckanext.archiver.plugin] New package - will archive
2020-06-04 20:55:46,216 DEBUG [ckanext.archiver.plugin] Creating archiver task: sspm-ingreso-inversion-extranjera-directa-bcra
2020-06-04 20:55:46,219 DEBUG [ckanext.archiver.lib] Archival of package put into celery queue priority: sspm-ingreso-inversion-extranjera-directa-bcra
2020-06-04 20:55:46,225 DEBUG [ckanext.spatial.plugin] Received: u'ARG'
2020-06-04 20:55:46,226 ERROR [ckanext.harvest.harvesters.base] {'spatial': [u'Error decoding JSON object: Expecting value: line 1 column 1 (char 0)']}
Traceback (most recent call last):
  File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/harvesters/base.py", line 372, in _create_or_update_package
    else 'package_create_rest')(context, package_dict)
  File "/usr/lib/ckan-new/src/ckan/ckan/logic/__init__.py", line 466, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan-new/src/ckan/ckan/logic/action/create.py", line 209, in package_create
    item.create(pkg)
  File "/usr/lib/ckan-new/src/ckanext-spatial/ckanext/spatial/plugin.py", line 90, in create
    self.check_spatial_extra(package)
  File "/usr/lib/ckan-new/src/ckanext-spatial/ckanext/spatial/plugin.py", line 115, in check_spatial_extra
    raise p.toolkit.ValidationError(error_dict, error_summary=package_error_summary(error_dict))
ValidationError: {'spatial': [u'Error decoding JSON object: Expecting value: line 1 column 1 (char 0)']}
2020-06-04 20:55:46,249 DEBUG [ckanext.harvest.model] Invalid package with GUID sspm_315: {'spatial': [u'Error decoding JSON object: Expecting value: line 1 column 1 (char 0)']}
```

**Comment by adborden** [comment]
:tada: sounds good enough to me. Let's make sure we have an issue for that and move on, I don't think the error is related to the sandbox setup.

**Comment by adborden** [comment]
@avdata99 can you confirm @woodt 's error is the same that is captured in https://github.com/GSA/catalog.data.gov/issues/55

**Comment by avdata99** [comment]
> @avdata99 can you confirm @woodt 's error is the same that is captured in [GSA/catalog.data.gov#55](https://github.com/GSA/catalog.data.gov/issues/55)

Yes, is the same error. In CKAN 2.3 fork we _roll up_ extras before save a package so the validation at spatial extension didn't see the spatial extra. In CKAN 2.8 we miss this _roll up_ function so the spatial capture the error. It's large to explain but yes, the error is the same.
The packages with spatial field will fail every time. We will fix this error at the [issue 55](https://github.com/GSA/catalog.data.gov/issues/55).

**Comment by woodt** [comment]
Excellent!  I reviewed all the errors, and found one more:

```
Invalid package with GUID agroindustria_c1e6c0a5-2e23-49ac-a80e-7ede4f1e6ac0: {'spatial': [u'Error creating geometry: Context does not provide geo interface']}
```

Is that also a known issue?

Regardless, I will go ahead and move this out of QA!   Andres, I'm not sure we have to co-work this morning :-)

@adborden @avdata99

**Comment by woodt** [comment]
Tested in sandbox with the harvest source Andres supplied above.  Test results described above.  Even though there are errors, I think we've met the acceptance criteria.

**Comment by avdata99** [comment]
> Excellent! I reviewed all the errors, and found one more:
> 
> ```
> Invalid package with GUID agroindustria_c1e6c0a5-2e23-49ac-a80e-7ede4f1e6ac0: {'spatial': [u'Error creating geometry: Context does not provide geo interface']}
> ```
> 
> Is that also a known issue?
> 
> Regardless, I will go ahead and move this out of QA! Andres, I'm not sure we have to co-work this morning :-)
> 
> @adborden @avdata99

No, I didn't get this error but maybe it's related to spatial. Maybe we need to do the same as in DCAT-US. To create a report on all harvest sources for CKAN to CKAN and WAF.
If we have some errors in those cases, we should start new issues.

**Comment by avdata99** [comment]
For the scope of this issue, we are done.
We have an error to see resources (maybe related to [NewCatalog#46](https://github.com/GSA/catalog.data.gov/issues/46)
@tom Can we activate debug in sandbox to see full errors?

**Comment by woodt** [comment]
Certainly, @adborden , although this second error is turning up in the harvester fetch, so I don't know if debug would help there?

is there existing practice about enabling debug that I should follow, or can i make up something in ansible :-?)

In the meantime, here's what is in the log with respect to the second error:

```
2020-06-04 20:52:03,047 INFO  [ckanext.harvest.harvesters.base] Package with GUID acumar_a9a46446-7a18-494b-8166-4f17e65f7ce9 does not exist, let's create it
2020-06-04 20:52:03,093 INFO  [ckanext.harvest.queue] Received harvest object id: 166df129-71d3-48f5-b853-bf2fe9b6854a
2020-06-04 20:52:03,117 DEBUG [ckanext.harvest.harvesters.ckanharvester] In CKANHarvester import_stage
2020-06-04 20:52:03,169 INFO  [ckanext.harvest.harvesters.base] Package with GUID acumar_b54dcccd-5efa-4908-b24e-a8c837b4e55d does not exist, let's create it
2020-06-04 20:52:03,291 DEBUG [ckanext.spatial.plugin] Received: u'["ARG", "02"]'
2020-06-04 20:52:03,297 ERROR [ckanext.harvest.harvesters.base] {'spatial': [u'Error creating geometry: Context does not provide geo interface']}
Traceback (most recent call last):
  File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/harvesters/base.py", line 372, in _create_or_update_package
    else 'package_create_rest')(context, package_dict)
  File "/usr/lib/ckan-new/src/ckan/ckan/logic/__init__.py", line 466, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan-new/src/ckan/ckan/logic/action/create.py", line 209, in package_create
    item.create(pkg)
  File "/usr/lib/ckan-new/src/ckanext-spatial/ckanext/spatial/plugin.py", line 90, in create
    self.check_spatial_extra(package)
  File "/usr/lib/ckan-new/src/ckanext-spatial/ckanext/spatial/plugin.py", line 125, in check_spatial_extra
    raise p.toolkit.ValidationError(error_dict, error_summary=package_error_summary(error_dict))
ValidationError: {'spatial': [u'Error creating geometry: Context does not provide geo interface']}
```

**Comment by adborden** [comment]
I'm not sure what you mean by "activating debug"? Is that a plugin? config option? logging level?

We've never done anything like that before, but I imagine its not hard to do either as a one-off ansible command `-e '{"catalog_ckan_plugins_additional": ["debug"]}'` or a permanent configuration option for sandbox.

In some cases we've bumped the logging level in production.ini, but this would make sense to implement with an Ansible variable.

**Comment by avdata99** [comment]
I think these errors @woodt should be new issues. Someone else should check for them.
Whit debug I mean the debug=True at then production.ini CKAN file.
Maybe we want to see full log errors while we QA something at the sandbox

**Comment by adborden** [comment]
QA is possibly blocked by https://github.com/GSA/datagov-ckan-multi/issues/321

**Comment by adborden** [comment]
We discussed the upstream behavior of ckanext-harvester vs our fork. The Harvest Sources tab and the controller serving that is a data.gov customization. For now, this behavior isn't essential to QA, so we'll go ahead.

**Comment by adborden** [comment]
There don't seem to be many CKAN-CKAN harvest sources. I tried DOI, but ran into https://github.com/GSA/datagov-ckan-multi/issues/325.

I used [Datos Argentina](https://catalog-next.sandbox.datagov.us/harvest/admin/4b26cadc-df44-479d-8934-e3d8ea49b889) source and it's looking good.

**Comment by avdata99** [comment]
> There don't seem to be many CKAN-CKAN harvest sources. I tried DOI, but ran into #325.
> 
> I used [Datos Argentina](https://catalog-next.sandbox.datagov.us/harvest/admin/4b26cadc-df44-479d-8934-e3d8ea49b889) source and it's looking good.

I'll try DoI source at my local.  assigned myself this issue

**Comment by avdata99** [comment]
Added [some notes](https://github.com/GSA/datagov-ckan-multi/issues/325#issuecomment-644067522), un-assign and moved to backlog to prioritize
