### ISSUE TITLE
catalog-next authentication in sandbox with login.gov

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#348]
## User Story

As a developer, I want to test catalog.data.gov authentication using login.gov in the sandbox

## Acceptance Criteria
- [ ] GIVEN that a test user account is created in the login.gov identity sandbox
- [ ] WHEN I visit the catalog login page I am redirected to login.gov
- [ ] THEN I can login using the test account credentials and
- [ ] THEN I am redirected back to the catalog application and
- [ ] THEN I am logged in.

## Details / tasks
- Configure a test team on the login.gov identity sandbox
- configure an application for catalog-next sandbox on the the login.gov identity sandbox:
  - Issuer string: something like urn:gov:gsa:SAML:2.0.profiles:sp:sso:datagovus:catalog-next-sandbox
  - PEM encoded public certificate
  - Return to app URL
  - Push notification URL
  - Redirect URL(s) after authentication
  - Desired profile attributes (note that to get more than e-mail and id we need IAL 2 identity proofing.)
- Retrieve idp metadata from https://idp.int.identitysandbox.gov/api/saml/metadata2020
- Based on Paul’s recent saml2 work, configure catalog-next

Note: it looks like login.gov does a POST back to the aapplication to deliver the SAML auth response. The existing saml2 repoze.who plugin seems to expect a GET request; some tweaks may be required.

**Comment by cmugisha** [comment]
Kim will start the process of breaking this ticket into smaller tickets. She will create a ticket about this task, "Configure a test team on the login.gov identity sandbox", estimate it to 3 story points, then move it to Current Sprint.

**Comment by woodt** [comment]
Reminder: after this is tested, should make sure GSA/pysaml2 feature/ci gets merged to master branch.

**Comment by woodt** [comment]
Update: we're now issuing successful requests to the login.gov SAML endpoint; the response back is generating an exception in pysaml2:

```
2020-10-09 16:00:48,411 INFO  [repoze.who] request classification: browser
2020-10-09 16:00:48,411 INFO  [repoze.who] -- repoze.who request started (/) --
2020-10-09 16:00:48,412 ERROR [saml2.entity] Signature Error: Signature missing for response
2020-10-09 16:00:48,413 ERROR [saml2.client_base] XML parse error: Signature missing for response
2020-10-09 16:00:48,413 ERROR [saml2.s2repoze.plugins.sp] Exception: Signature missing for response
Traceback (most recent call last):
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/s2repoze/plugins/sp.py", line 423, in _eval_authn_response
    self.outstanding_certs,
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/client_base.py", line 714, in parse_authn_request_response
    binding, **kwargs)
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/entity.py", line 1142, in _parse_response
    response = response.loads(xmlstr, False, origxml=xmlstr)
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/response.py", line 522, in loads
    self._loads(xmldata, decode, origxml)
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/response.py", line 342, in _loads
    **args)
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/sigver.py", line 1645, in correctly_signed_response
    raise SignatureError('Signature missing for response')
SignatureError: Signature missing for response
```

**Comment by woodt** [comment]
Just to capture all the work here:

https://github.com/GSA/catalog.data.gov/tree/enable-saml2

https://github.com/GSA/ckanext-saml2/tree/datagov/v0.4.0-login.gov

https://github.com/GSA/datagov-deploy/tree/catalog-next-saml

**Comment by woodt** [comment]
Signature verification issue has been resolved (spun up new login.gov config in ckanext-saml2)
Updated SAML2 attribute mapping to match login.gov (uses different identifiers than max.gov)

Still not getting a valid identity back from the pysaml2 repoze.who plugin identify() method.  Debugging.

**Comment by woodt** [comment]
Aha.  It was a silently caught exception!

```
2020-10-20 19:24:57,642 ERROR [saml2.s2repoze.plugins.sp] [sp.identify] saml_error
Traceback (most recent call last):
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/s2repoze/plugins/sp.py", line 544, in identify
    environ, post, binding=binding
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/s2repoze/plugins/sp.py", line 430, in _eval_authn_response
    session_info = authresp.session_info()
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/response.py", line 1108, in session_info
    authn_statement = self.assertion.authn_statement[0]
AttributeError: 'NoneType' object has no attribute 'authn_statement'
```

**Comment by woodt** [comment]
The game is afoot.

```
2020-10-20 19:46:05,785 ERROR [saml2.response] find_encrypt_data; failed to decrypt
Traceback (most recent call last):
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/response.py", line 952, in parse_assertion
    decr_text = self.sec.decrypt_keys(decr_text, keys)
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/sigver.py", line 1373, in decrypt_keys
    dectext = self.decrypt(enctext, key_file=key_files, id_attr=id_attr)
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/sigver.py", line 1408, in decrypt
    raise DecryptError(errmsg)
DecryptError: No key was able to decrypt the ciphertext. Keys tried: []
```

**Comment by woodt** [comment]
Tracked this down to an apparent bug(?) in pysaml repoze plugin.  The configuration for handling signed assertions doesn't seem to pass the correct keys down the stack.  Trying out a fix.  If this doesn't work, may try to disable assertion signing.

**Comment by woodt** [comment]
Fix + sid_store_cert configuration did *not* seem to fix the problem ... still not seeing any keys passed to assertion decrypt.  And, disabling `want_signed_assertions` in the login.gov config in ckanext-saml2 did not seem to disable assertion signing.  Reviewing the logs again.  I suspect the first problem might be due to a problem with the challenger() method  -- hypothesis: some state that is expected to be passed from the challenge phase to the identify phase is not being passed correctly.  Next attempt to debug will be to determine if the saml2 challenger decider is running correctly.

Per Wednesday's scrum, I am setting up a meeting with Patricio at Datopian to get some more help on debugging this.

**Comment by jbrown-xentity** [comment]
@woodt I would love to pair with you on this next time you pick it up...

**Comment by woodt** [comment]
Met with Patricio ... he has sent me some other repos to look at that he thought might help (will include them here.)

**Comment by woodt** [comment]
Discovered that login.gov seems to ignore the WantAssertionsSigned bit of metadata in the SP config; however, setting the assertion crypto system in the login.gov app configuration appears to disable assertion signing!  We're now able to decode the assertions, which gets us to the next issue: an unknown attribute name format.  This is probably fixable :-)

**Comment by woodt** [comment]
As a test, I set `allow_unknown_attributes` to true in the SP config, and that it appears that we are now able to successfully parse assertions, and the SAML2 plugin returns an authenticated ID!  It doesn't seem like that is still good enough for the downstream middleware, though.   Still investigating.

**Comment by woodt** [comment]
After reviewing the code, my current hypothesis is that the attribute conversion is failing to produce values that can be used to construct a consumable identity.  I've written a new attribute map specifically for login.gov and will try that out later today.

ansible/roles/software/ckan/catalog/ckan-app/files/saml2/login_gov.py in catalog-next-saml branch of datagov-deploy

**Comment by woodt** [comment]
Tried out the new attribute map.  Although pysaml appeared to read it (e.g., a .pyc file was generated), it did not seem to actually use the map while processing assertions.  There may be an ordering issue -- it is processing the basic map first, which fails.  Regardless, I manually added the attributes from login_gov.py to the basic map and we got quite a bit further, eventually failing in some ckan code in ckan/views/__init__.py, trying to handle a failure in locating a CKAN user object.

Next steps:
- Although the attributes are now being read, and an actual repose.who identity is constructed, I think the 'login' attribute is incorrect (it's kind of a mess, and is in fact not a valid CKAN user id.)   Probably need to write a custom converter, which should not be difficult

**Comment by woodt** [comment]
Here's the login identifier being returned (current): 

```
2020-11-16 22:03:01,661 DEBUG [ckanext.saml2] REMOTE_USER = "2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=65455"
```

**Comment by woodt** [comment]
Here's the relevant bit of the log file showing the current failure:

```
2020-11-16 22:03:01,349 ERROR [saml2.sigver] ==== Certs from metadata ==== https://idp.int.identitysandbox.gov/api/saml: [(<open file '<fdopen>', mode 'w+b' at 0x7fc0dbd4b5d0>, '/tmp/tmpVbv0fT.pem'), (<open file '<fdopen>', mode 'w+b' at 0x7fc0dba269c0>, '/tmp/tmpMv8qrU.pem')] ====
2020-11-16 22:03:01,350 ERROR [saml2.sigver] xmlsec command: /usr/bin/xmlsec1 --verify --enabled-reference-uris empty,same-doc --pubkey-cert-pem /tmp/tmpVbv0fT.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:assertion:Assertion --node-id _f91bc758-3f41-4873-9385-a8867327355f --output /tmp/tmpXRaDTD.xml /tmp/tmpoI283c.xml
2020-11-16 22:03:01,419 ERROR [saml2.response] assertion context: AuthnReq
2020-11-16 22:03:01,422 ERROR [saml2.response] assertion keys: ['authn_statement', 'attribute_statement', 'subject', 'issue_instant', 'version', 'signature', 'conditions', 'id', 'issuer']
2020-11-16 22:03:01,425 ERROR [saml2.response] outstanding_queries: {'id-r6KJiwMTJ7DNTJwAz': '/user/login', 'id-FNwkgjwLgfb6yRBmt': '/user/login'}
2020-11-16 22:03:01,426 ERROR [saml2.response] conditions: <?xml version='1.0' encoding='UTF-8'?>
<ns0:Conditions xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" NotBefore="2020-11-16T22:02:55Z" NotOnOrAfter="2020-11-16T23:03:00Z"><ns0:AudienceRestriction><ns0:Audience>urn:gov:gsa:SAML:2.0.profiles:sp:sso:datagovus:catalog-next-sandbox</ns0:Audience></ns0:AudienceRestriction></ns0:Conditions>
2020-11-16 22:03:01,436 ERROR [saml2.response] --- Getting Identity ---
2020-11-16 22:03:01,438 ERROR [saml2.response] Subject NameID: <?xml version='1.0' encoding='UTF-8'?>
<ns0:NameID xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">65455</ns0:NameID>
2020-11-16 22:03:01,438 ERROR [saml2.response] Assertion contains 1 attribute statement(s)
2020-11-16 22:03:01,439 ERROR [saml2.response] Attribute Statement: <?xml version='1.0' encoding='UTF-8'?>
<ns0:AttributeStatement xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><ns0:Attribute FriendlyName="uuid" Name="uuid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><ns0:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">ca21a25a-564e-435d-af11-4a3d466ba088</ns0:AttributeValue></ns0:Attribute><ns0:Attribute FriendlyName="email" Name="email" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><ns0:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">thomas.wood@gsa.gov</ns0:AttributeValue></ns0:Attribute></ns0:AttributeStatement>
2020-11-16 22:03:01,439 ERROR [saml2.response] Attribute Statement: <?xml version='1.0' encoding='UTF-8'?>
<ns0:AttributeStatement xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><ns0:Attribute FriendlyName="uuid" Name="uuid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><ns0:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">ca21a25a-564e-435d-af11-4a3d466ba088</ns0:AttributeValue></ns0:Attribute><ns0:Attribute FriendlyName="email" Name="email" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><ns0:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">thomas.wood@gsa.gov</ns0:AttributeValue></ns0:Attribute></ns0:AttributeStatement>
2020-11-16 22:03:01,448 ERROR [saml2.response] --- AVA: {'uuid': [u'ca21a25a-564e-435d-af11-4a3d466ba088'], 'email': [u'thomas.wood@gsa.gov']}
2020-11-16 22:03:01,452 ERROR [saml2.s2repoze.plugins.sp] Session_info: {'authn_info': [('http://idmanagement.gov/ns/assurance/ial/1', [], '2020-11-16T22:03:00Z')], 'name_id': <saml2.saml.NameID object at 0x7fc0db2fc050>, 'not_on_or_after': 1605567780, 'session_index': '_f91bc758-3f41-4873-9385-a8867327355f', 'came_from': None, 'ava': {'uuid': [u'ca21a25a-564e-435d-af11-4a3d466ba088'], 'email': [u'thomas.wood@gsa.gov']}, 'issuer': 'https://idp.int.identitysandbox.gov/api/saml'}
2020-11-16 22:03:01,453 ERROR [saml2.s2repoze.plugins.sp] [sp.identify] session_info: {'authn_info': [('http://idmanagement.gov/ns/assurance/ial/1', [], '2020-11-16T22:03:00Z')], 'name_id': <saml2.saml.NameID object at 0x7fc0db2fc050>, 'not_on_or_after': 1605567780, 'session_index': '_f91bc758-3f41-4873-9385-a8867327355f', 'came_from': None, 'ava': {'uuid': [u'ca21a25a-564e-435d-af11-4a3d466ba088'], 'email': [u'thomas.wood@gsa.gov']}, 'issuer': 'https://idp.int.identitysandbox.gov/api/saml'}
2020-11-16 22:03:01,455 ERROR [saml2.s2repoze.plugins.sp] Identity: {'login': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=65455', 'password': '', 'repoze.who.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=65455', 'user': {'uuid': [u'ca21a25a-564e-435d-af11-4a3d466ba088'], 'email': [u'thomas.wood@gsa.gov']}}
2020-11-16 22:03:01,456 DEBUG [repoze.who] identity returned from <saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7fc0db836a50>: {'login': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=65455', 'password': '', 'repoze.who.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=65455', 'user': {'uuid': [u'ca21a25a-564e-435d-af11-4a3d466ba088'], 'email': [u'thomas.wood@gsa.gov']}}
2020-11-16 22:03:01,457 DEBUG [repoze.who] no identity returned from <AuthTktCookiePlugin 140466293816592> (None)
2020-11-16 22:03:01,457 DEBUG [repoze.who] identities found: [(<saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7fc0db836a50>, {'login': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=65455', 'password': '', 'repoze.who.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=65455', 'user': {'uuid': [u'ca21a25a-564e-435d-af11-4a3d466ba088'], 'email': [u'thomas.wood@gsa.gov']}})]
2020-11-16 22:03:01,457 DEBUG [repoze.who] authenticator plugins registered: [<saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7fc0db836a50>, <AuthTktCookiePlugin 140466293816592>]
2020-11-16 22:03:01,457 DEBUG [repoze.who] authenticator plugins matched for classification "browser": [<saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7fc0db836a50>, <AuthTktCookiePlugin 140466293816592>]
2020-11-16 22:03:01,458 DEBUG [repoze.who] userid returned from <saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7fc0db836a50>: "2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=65455"
2020-11-16 22:03:01,458 DEBUG [repoze.who] no userid returned from <AuthTktCookiePlugin 140466293816592>: (None)
2020-11-16 22:03:01,458 DEBUG [repoze.who] identities authenticated: [((0, 0), <saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7fc0db836a50>, <saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7fc0db836a50>, {'login': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=65455', 'password': '', 'repoze.who.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0
```

**Comment by woodt** [comment]
After going through the logs and reading the pysaml2, ckanext-saml2 and ckan code, my current hypothesis is that we are entering the ckanext-saml2  IAuthenticator.identify() plugin entry point, but that is failing to establish a user, so we then drop into the default ckan identification, which blows up.

So: (1) I need to test the hypothesis, and then (2) debug plugin.py:identify() in ckanext-saml2.

**Comment by cmugisha** [comment]
Tom and Julie will add some unit tests in the SAML2 forks.

**Comment by woodt** [comment]
Login and automatic user creation now working.  Still need to resolve:
- logout (failing)
- how to handle login.gov attribute map w/o breaking the catalog (max.gov) side

Needed to add saml2auth repoze.who plugin to a new [mdproviders] section of the who.ini file.
Needed to enable saml2.name_id_from_saml2_NameID = true to get user account creation to work properly.

PRs updated.

**Comment by woodt** [comment]
Rebased the catalog.data.gov and datagov-deploy PRs and tested (successful).

Still investigating the logout issue.  "Someone", "somewhere" is generating an exception (does not appear in the log) which manifests as an "internal server error" string appearing in template block.  Also, the actual logout is *not* happening.

**Comment by avdata99** [comment]
logs for the `logout` call

```
=> /var/log/ckan/gunicorn.log <==
2020-11-23 16:30:27,687 DEBUG [ckan.config.middleware.flask_app] Flask route match, endpoint: user.logout, args: {}, origin: core
2020-11-23 16:30:27,688 DEBUG [ckan.config.middleware.pylons_app] Pylons route match: {'url': u'user/_logout', 'action': u'view', 'controller': u'template'} Origin: core
2020-11-23 16:30:27,688 DEBUG [ckan.config.middleware] Route support answers for GET /user/_logout: [(True, 'flask_app', 'core'), (True, 'pylons_app', 'core')]
2020-11-23 16:30:27,688 DEBUG [ckan.config.middleware] Serving request via flask_app app
2020-11-23 16:30:27,689 INFO  [repoze.who] request classification: browser
2020-11-23 16:30:27,689 INFO  [repoze.who] -- repoze.who request started (/user/_logout) --
2020-11-23 16:30:27,690 DEBUG [repoze.who] identifier plugins registered: [<saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7f990798d8d0>, <AuthTktCookiePlugin 140295235433808>]
2020-11-23 16:30:27,690 DEBUG [repoze.who] identifier plugins matched for classification "browser": [<saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7f990798d8d0>, <AuthTktCookiePlugin 140295235433808>]
2020-11-23 16:30:27,690 ERROR [saml2.s2repoze.plugins.sp] [sp.identify] uri: https://catalog-next.sandbox.datagov.us/user/_logout
2020-11-23 16:30:27,690 ERROR [saml2.s2repoze.plugins.sp] [sp.identify] query: MultiDict([])
2020-11-23 16:30:27,691 ERROR [saml2.s2repoze.plugins.sp] [identify] get or empty post
2020-11-23 16:30:27,691 DEBUG [repoze.who] no identity returned from <saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7f990798d8d0> (None)
2020-11-23 16:30:27,691 DEBUG [repoze.who] identity returned from <AuthTktCookiePlugin 140295235433808>: {'tokens': [''], 'timestamp': 1605902172, 'repoze.who.plugins.auth_tkt.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664', 'userdata': {}}
2020-11-23 16:30:27,692 DEBUG [repoze.who] identities found: [(<AuthTktCookiePlugin 140295235433808>, {'tokens': [''], 'timestamp': 1605902172, 'repoze.who.plugins.auth_tkt.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664', 'userdata': {}})]
2020-11-23 16:30:27,692 DEBUG [repoze.who] authenticator plugins registered: [<saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7f990798d8d0>, <AuthTktCookiePlugin 140295235433808>]
2020-11-23 16:30:27,692 DEBUG [repoze.who] authenticator plugins matched for classification "browser": [<saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7f990798d8d0>, <AuthTktCookiePlugin 140295235433808>]
2020-11-23 16:30:27,692 DEBUG [repoze.who] no userid returned from <saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7f990798d8d0>: (None)
2020-11-23 16:30:27,693 DEBUG [repoze.who] userid returned from <AuthTktCookiePlugin 140295235433808>: "2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664"
2020-11-23 16:30:27,693 DEBUG [repoze.who] identities authenticated: [((1, 0), <AuthTktCookiePlugin 140295235433808>, <AuthTktCookiePlugin 140295235433808>, {'tokens': [''], 'timestamp': 1605902172, 'repoze.who.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664', 'repoze.who.plugins.auth_tkt.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664', 'userdata': {}}, '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664')]
2020-11-23 16:30:27,693 ERROR [saml2.s2repoze.plugins.sp] [add_metadata] for <?xml version='1.0' encoding='UTF-8'?>
<ns0:NameID xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">99664</ns0:NameID>
2020-11-23 16:30:27,694 ERROR [saml2.s2repoze.plugins.sp] Issuers: ['https://idp.int.identitysandbox.gov/api/saml']
2020-11-23 16:30:27,694 ERROR [saml2.s2repoze.plugins.sp] [add_metadata] adds: {}
2020-11-23 16:30:27,694 ERROR [saml2.s2repoze.plugins.sp] [add_metadata] returns: {'tokens': [''], 'userdata': {}, 'repoze.who.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664', 'timestamp': 1605902172, 'repoze.who.plugins.auth_tkt.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664', 'authenticator': <AuthTktCookiePlugin 140295235433808>, 'user': {}, 'identifier': <AuthTktCookiePlugin 140295235433808>}
2020-11-23 16:30:27,702 DEBUG [ckanext.saml2] REMOTE_USER = "2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664"
2020-11-23 16:30:27,702 DEBUG [ckanext.saml2] NameId: 99664
2020-11-23 16:30:27,709 DEBUG [ckanext.saml2] saml2_user_info = (<ckanext.saml2.model.saml2_user.SAML2User object at 0x7f9906443550>, <User id=f1a96f90-c0b4-4286-a889-8280f1805448 name=julie-kramer-1934 password=$pbkdf2-sha512$25000$zblXSqmV8r43JqQUonQuJQ$dqKlj/SKwIWSN7y/VIZEJi3dNiTjP/Exc0Zt4Zxq3QyyFKT6Y/aE9O9xHgJznaGCcQ7BWJdEqn0v9Lqlxx/f9g fullname=julie.kramer@gsa.gov email=julie.kramer@gsa.gov apikey=40c23862-de07-4d82-abd0-90f3c46c1788 created=2020-11-20 19:56:13.126506 reset_key=None about=None activity_streams_email_notifications=False sysadmin=False state=active>)
2020-11-23 16:30:27,710 DEBUG [ckanext.saml2] identify(): c.user = u'julie-kramer-1934'
2020-11-23 16:30:27,710 DEBUG [ckanext.saml2] repoze.who.identity = {'tokens': [''], 'userdata': {}, 'repoze.who.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664', 'timestamp': 1605902172, 'repoze.who.plugins.auth_tkt.userid': '2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664', 'authenticator': <AuthTktCookiePlugin 140295235433808>, 'user': {}, 'identifier': <AuthTktCookiePlugin 140295235433808>}
2020-11-23 16:30:27,710 DEBUG [ckanext.saml2] identify(): saml_info = {}
2020-11-23 16:30:27,720 DEBUG [ckan.logic] check access OK - user_show user=julie-kramer-1934
2020-11-23 16:30:27,739 DEBUG [ckan.logic] check access OK - site_read user=julie-kramer-1934
2020-11-23 16:30:27,745 DEBUG [ckanext.saml2] logout(): sp_initiates_slo=True userobj=<User id=f1a96f90-c0b4-4286-a889-8280f1805448 name=julie-kramer-1934 password=$pbkdf2-sha512$25000$zblXSqmV8r43JqQUonQuJQ$dqKlj/SKwIWSN7y/VIZEJi3dNiTjP/Exc0Zt4Zxq3QyyFKT6Y/aE9O9xHgJznaGCcQ7BWJdEqn0v9Lqlxx/f9g fullname=julie.kramer@gsa.gov email=julie.kramer@gsa.gov apikey=40c23862-de07-4d82-abd0-90f3c46c1788 created=2020-11-20 19:56:13.126506 reset_key=None about=None activity_streams_email_notifications=False sysadmin=False state=active> is_local_user=False
2020-11-23 16:30:27,750 DEBUG [ckanext.saml2] logout(): subject_id='2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Apersistent,4=99664', name_id=<saml2.saml.NameID object at 0x7f99062c0f90>, client=<saml2.s2repoze.plugins.sp.SAML2Plugin object at 0x7f990798d8d0>
2020-11-23 16:30:27,764 DEBUG [ckan.logic] check access OK - dashboard_new_activities_count user=julie-kramer-1934
2020-11-23 16:30:27,765 DEBUG [ckan.logic] check access OK - dashboard_activity_list user=julie-kramer-1934

2020-11-23 16:30:27,902 INFO  [repoze.who] no challenge required
2020-11-23 16:30:27,902 INFO  [repoze.who] -- repoze.who request ended (/user/_logout) --

==> /var/log/ckan/ckan.access.log <==
187.170.15.106 - - [23/Nov/2020:16:30:27 +0000] "GET /user/_logout HTTP/1.1" 500 23209 "https://catalog-next.sandbox.datagov.us/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
```

**Comment by thejuliekramer** [comment]
PR's to review 

https://github.com/GSA/catalog.data.gov/pull/121

https://github.com/GSA/ckanext-saml2/pull/11

https://github.com/GSA/datagov-deploy/pull/2202

**Comment by thejuliekramer** [comment]
@woodt I added some comments and rebased the GSA/datagov-deploy#2202 PR because the tests were failing - tests are fixed but just be aware when you pull the branch it is rebased

**Comment by thejuliekramer** [comment]
@adborden We've merged the PR's needed in ckanext-saml2, pysaml2, and catalog.data.gov. Would you mind reviewing the PR for datagov deploy before we merge? Everything is working well in Sandbox

https://github.com/GSA/datagov-deploy/pull/2202

**Comment by thejuliekramer** [comment]
@adborden this is ready for QA on [Sandbox](https://catalog-next.sandbox.datagov.us/dataset)

**Comment by adborden** [comment]
I was able to login successfully with my login.gov test account and MFA.

**Comment by adborden** [comment]
@thejuliekramer @woodt before we close this, can we fix the branch names? I'm seeing a feature branch in the toml config for [pysaml2](https://github.com/GSA/catalog.data.gov/blob/master/requirements/pyproject.toml#L92) (should be datagov/v4.9.0 by our convention) and [ckanext-saml2](https://github.com/GSA/catalog.data.gov/blob/master/requirements/pyproject.toml#L24) (should be datagov/v0.4.0).

**Comment by woodt** [comment]
Created https://github.com/GSA/pysaml2/pull/6 to update datagov/v4.9.0 per @adborden's suggestion.

**Comment by woodt** [comment]
Created https://github.com/GSA/ckanext-saml2/pull/12 to update datagov/v0.4.0 ... I think this needs some love before merging.  Not sure why so much config is getting created; vestiges of Paul's old work?

**Comment by adborden** [comment]
🤦  @woodt bummer, it's already merged. Right, I think this is based on the wrong branch. I don't think there was anything from the old branch that we wanted. We should've rebased to datagov/v0.4.0 and dropped the old commits. Let me take a look and see what needs to happen.

**Comment by thejuliekramer** [comment]
@adborden I'm looking at this now too - I left some comments in Slack. If its ok with you I can revert the commits from here 

<img width="513" alt="Screen Shot 2020-12-09 at 2 51 35 PM" src="https://user-images.githubusercontent.com/7378770/101687363-0021fa00-3a30-11eb-9d14-33e8b917d9a0.png">
and merge this branch (rebased with v4.9.0) after https://github.com/GSA/pysaml2/pull/7

**Comment by thejuliekramer** [comment]
PR to revert commits https://github.com/GSA/pysaml2/pull/8

**Comment by thejuliekramer** [comment]
@adborden Updated branches of [pysaml2](https://github.com/GSA/pysaml2/) and [ckanext-saml2](https://github.com/GSA/ckanext-saml2) and redeployed to [sandbox](https://catalog-next.sandbox.datagov.us/dataset). Ready for your review again (if it isn't working it is because the SAML Assertion Encryption is turned on you can turn it off [here](https://dashboard.int.identitysandbox.gov/service_providers/1129/edit?)

**Comment by adborden** [comment]
Thanks, l think there's still some max commits in [ckanext-saml2](https://github.com/GSA/ckanext-saml2/commits/datagov/v0.4.0) but we can drop them the next time we rebase.

**Comment by adborden** [comment]
Sandbox is looking good for the new saml2auth extension.
