### ISSUE TITLE
catalog-next db init fails: sqlalchemy.exc.NoSuchTableError: harvest_object

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#379]
Getting two stack traces when trying to [initialize the database in staging](https://github.com/GSA/datagov-ckan-multi/issues/296#issuecomment-670771206):

Running: `sudo -u www-data /usr/lib/ckan/bin/paster --plugin=ckan db init -c /etc/ckan/production.ini`

```
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan-new/src/ckan/ckan/lib/cli.py", line 363, in command
    model.repo.init_db()
  File "/usr/lib/ckan-new/src/ckan/ckan/model/__init__.py", line 188, in init_db
    self.upgrade_db()
  File "/usr/lib/ckan-new/src/ckan/ckan/model/__init__.py", line 266, in upgrade_db
    mig.upgrade(self.metadata.bind, self.migrate_repository, version=version)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "<decorator-gen-16>", line 2, in _migrate
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 160, in with_engine
    return f(*a, **kw)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/migrate/versioning/api.py", line 366, in _migrate
    schema.runchange(ver, change, changeset.step)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/migrate/versioning/schema.py", line 93, in runchange
    change.run(self.engine, step)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/migrate/versioning/script/py.py", line 148, in run
    script_func(engine)
  File "/usr/lib/ckan-new/src/ckan/ckan/migration/versions/028_drop_harvest_source_status.py", line 14, in upgrade
    harvested_source_table.c.status.drop()
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/migrate/changeset/schema.py", line 592, in drop
    engine._run_visitor(visitorcallable, self, connection, **kwargs)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1929, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1538, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/migrate/changeset/ansisql.py", line 56, in traverse_single
    ret = super(AlterTableVisitor, self).traverse_single(elem)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/migrate/changeset/ansisql.py", line 141, in visit_column
    self.execute()
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/migrate/changeset/ansisql.py", line 44, in execute
    return self.connection.execute(self.buffer.getvalue())
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "status" of relation "harvest_source" does not exist
 [SQL: '\nALTER TABLE harvest_source DROP COLUMN status']
```

```
2020-08-07 22:59:21,394 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2020-08-07 22:59:21,416 DEBUG [ckanext.harvest.model] Harvest tables already exist
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan-new/src/ckan/ckan/lib/cli.py", line 357, in command
    self._load_config(cmd!='upgrade')
  File "/usr/lib/ckan-new/src/ckan/ckan/lib/cli.py", line 330, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/usr/lib/ckan-new/src/ckan/ckan/lib/cli.py", line 237, in load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan-new/src/ckan/ckan/config/environment.py", line 116, in load_environment
    p.load_all()
  File "/usr/lib/ckan-new/src/ckan/ckan/plugins/core.py", line 140, in load_all
    load(*plugins)
  File "/usr/lib/ckan-new/src/ckan/ckan/plugins/core.py", line 168, in load
    plugins_update()
  File "/usr/lib/ckan-new/src/ckan/ckan/plugins/core.py", line 122, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan-new/src/ckan/ckan/config/environment.py", line 292, in update_config
    plugin.configure(config)
  File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/plugin/__init__.py", line 226, in configure
    model_setup()
  File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/model/__init__.py", line 78, in setup
    index_names = [index['name'] for index in inspector.get_indexes("harvest_object")]
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 481, in get_indexes
    info_cache=self.info_cache, **kw)
  File "<string>", line 2, in get_indexes
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2723, in get_indexes
    info_cache=kw.get('info_cache'))
  File "<string>", line 2, in get_table_oid
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2340, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: harvest_object
```

## How to reproduce

On catalogharvester1d:

1. `sudo -u www-data /usr/lib/ckan/bin/paster --plugin=ckan db init -c /etc/ckan/production.ini`

## Expected behavior

Base CKAN tables are initialized.

## Actual behavior

Initialization fails part way through.

**Comment by adborden** [comment]
One thing that bugs me that we'll want to follow up on is why we get a different error the second time. It looks like the migration fails but does not roll back the transaction. Is there a manual rollback necessary or should we report this upstream to CKAN?

**Comment by avdata99** [comment]
Since [the staging environment it's working](https://github.com/GSA/datagov-ckan-multi/issues/296#issuecomment-681126830): should we close this?
The status field is added in the [migration 23](https://github.com/ckan/ckan/blob/2.8/ckan/migration/versions/023_add_harvesting.py#L17). The migration maybe started from a bad position.

**Comment by adborden** [comment]
The staging environment is only working because I had to work-around the issue.

Let's keep this open, but we can say we need a better repo. I'm pretty sure we'll run into this again when we setup production.

**Comment by adborden** [comment]
I just ran into this again.
```
createuser -h $DB_HOST -U $DB_ADMIN_USER -S -D -R -P ckan
psql -h $DB_HOST -U $DB_ADMIN_USER -c "GRANT ckan to $DB_ADMIN_USER;" postgres
createdb -h $DB_HOST -U $DB_ADMIN_USER -O ckan ckan -E utf-8
psql -h $DB_HOST -U $DB_ADMIN_USER -d ckan -c 'CREATE EXTENSION postgis;'
sudo /usr/lib/ckan/bin/paster --plugin=ckan db init -c /etc/ckan/production.ini
```
