### ISSUE TITLE
catalog-next harvesters fail to connect to redis on staging, triggers CPU alerts

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#387]
Seeing this on harvest-run, harvest-gather, and harvest-fetch:
```
2020-08-13 00:20:45,482 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered

Traceback (most recent call last):
  File "/usr/bin/ckan", line 45, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 209, in command
    utils.fetch_consumer()
  File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/utils.py", line 336, in fetch_consumer
    for method, header, body in consumer.consume(queue=get_fetch_queue_name()):
  File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/queue.py", line 254, in consume
    key, body = self.redis.blpop(self.routing_key)
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/client.py", line 1900, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/connection.py", line 649, in on_connect
    self.send_command('AUTH', self.password, check_health=False)
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/connection.py", line 725, in send_command
    self.send_packed_command(self.pack_command(*args),
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/connection.py", line 775, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/connection.py", line 120, in encode
    "bytes, string, int or float first." % typename)
redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.
```

We also see [CPU alerts](https://one.newrelic.com/launcher/nrai.launcher?pane=eyJuZXJkbGV0SWQiOiJhbGVydGluZy11aS1jbGFzc2ljLmluY2lkZW50cyIsIm5hdiI6IkluY2lkZW50cyIsImluY2lkZW50SWQiOiIxNTEyMTQyMzAifQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucmFpLm5hdmlnYXRpb24tYmFyIiwibmF2IjoiSW5jaWRlbnRzIn0=&platform[accountId]=1601367&platform[timeRange][duration]=604800000&platform[$isFallbackTimeRange]=true) because of this.

## How to reproduce

From catalogharvester1d:

1. `sudo supervisorctl start harvest-gather`
1. `sudo tail -f /var/log/gather-consumer.log`

## Expected behavior

Harvest processes idle, no exception is thrown

## Actual behavior

Exception thrown.

**Comment by woodt** [comment]
Confirmed that the harvest jobs on catalogharvester1d can connect to redis.
