### ISSUE TITLE
Create turn-key capability to edit OpenControl content (probably using Docker)

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#68]

**Comment by woodt** [comment]
I'm thinking of something like this ...

```
git clone <repo>.git
cd <repo>
bin/hypergrc
```

The shell script will either use the `hypergrc` Docker image, or possibly build a new image, start a container with `_data/opencontrol` mounted in the right place.

**Comment by adborden** [comment]
@woodt Are these instructions still correct? Am I in the right repo?
```
gsa@cano ~/projects/datagov/datagov-ckan-multi
(master {1} ?:2 ✗) $ bin/hypergc
-bash: bin/hypergc: No such file or directory
```

**Comment by woodt** [comment]
Instructions are wrong!  I will update the README.  In the interim,

```
$ npm install
$ npm run-script edit-controls
```

should do the trick.

**Comment by adborden** [comment]
Thanks @woodt I'll add this to the Readme.

BTW, I got this error when trying to edit a control. Is this expected?

```
172.17.0.1 - - [23/Jul/2019 17:48:53] "POST /update-control HTTP/1.1" 500 -
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 49930)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/src/app/hypergrc/__main__.py", line 88, in do_POST
    self.do_request("POST")
  File "/usr/src/app/hypergrc/__main__.py", line 142, in do_request
    resp = route_function(self, **m)
  File "/usr/src/app/hypergrc/routes.py", line 980, in update_control
    if opencontrol.update_component_control(controlimpl):
  File "/usr/src/app/hypergrc/opencontrol.py", line 710, in update_component_control
    with open(controlimpl["source_file"], "r+", encoding="utf8") as f:
PermissionError: [Errno 13] Permission denied: '/opencontrol/components/CKAN/AC-ACCESS_CONTROL.yaml'
----------------------------------------
```

**Comment by JJediny** [comment]
editing controls from the Readme in `/_data/opencontrol` is working for me to stand up hypergrc in docker; but need to agree on the concept of editing one `component.yaml` file vs one yaml file for each control family

**Comment by woodt** [comment]
@adborden No, I don't think that error is expected.  What OS and Docker version are you using?

**Comment by adborden** [comment]
I opened https://github.com/GSA/datagov-ckan-multi/issues/94 re: the editing issue.

@JJediny do you want to open another issue for that? I think we can call this issue done.
