### ISSUE TITLE
HyperGRC editing fails on Linux with permission denied

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#94]
Running on Linux, I tried editing a control with HyperGRC and it failed.
Ubuntu 18.04
Docker version 18.09.7, build 2d0083d
```
172.17.0.1 - - [23/Jul/2019 17:48:53] "POST /update-control HTTP/1.1" 500 -
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 49930)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/src/app/hypergrc/__main__.py", line 88, in do_POST
    self.do_request("POST")
  File "/usr/src/app/hypergrc/__main__.py", line 142, in do_request
    resp = route_function(self, **m)
  File "/usr/src/app/hypergrc/routes.py", line 980, in update_control
    if opencontrol.update_component_control(controlimpl):
  File "/usr/src/app/hypergrc/opencontrol.py", line 710, in update_component_control
    with open(controlimpl["source_file"], "r+", encoding="utf8") as f:
PermissionError: [Errno 13] Permission denied: '/opencontrol/components/CKAN/AC-ACCESS_CONTROL.yaml'
----------------------------------------
```

## How to reproduce

1. `npm run edit-controls`
1. Open a control from a component http://localhost:8000/organizations/GSA-338246/projects/Data.gov+Mul-581f9e/components/CKAN
1. Make an edit, click Save

## Expected behavior

Save is valid, changes saved to `_data/opencontrol/components/CKAN/AC-ACCESS_CONTROL.yaml`.

## Actual behavior

Error, edits not saved.

**Comment by adborden** [comment]
I believe it's a uid mismatch issue.
```
$ docker run --rm -it  --entrypoint /bin/sh hypergrc:latest -c id -u
uid=1000(application) gid=1000(application) groups=1000(application)

$ id -u
1001
```
